package net.thep2wking.oedldoedlcuriosity.init;

import baubles.api.BaubleType;
import net.minecraft.init.MobEffects;
import net.minecraft.init.SoundEvents;
import net.minecraft.item.Item;
import net.thep2wking.oedldoedlcore.api.item.ModItemBase;
import net.thep2wking.oedldoedlcore.api.item.ModItemBlockBase;
import net.thep2wking.oedldoedlcore.util.ModRarities;
import net.thep2wking.oedldoedlcuriosity.OedldoedlCuriosity;
import net.thep2wking.oedldoedlcuriosity.api.ModItemBaubleBase;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemAmazingTechnicolorGlasses;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemAngelRing;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemArgentoriumAmulet;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemBalancedNecklace;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemBedrockiumRing;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemBirdsNest;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemBlueKyoryuuHorns;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemBunnyCap;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemBunnyEars;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemCatEars;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemChainsawHat;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemCrown;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemTopHat;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemDemonicWings;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemDevilHorns;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemDevilTail;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemDevilWings;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemFakeArrow;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemFancySunglasses;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemFlyingShootingBasecap;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemGlasses;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemGooglyEyes;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemGremoriumAmulet;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemHimejimariumAmulet;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemJoint;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemKitagawariumAmulet;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemKittyHeadset;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemLeafHeadband;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemMeguminHat;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemMeguminPantsu;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemMinepods;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemMinepodsMax;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemMinepodsPro;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemMonocle;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemMoustage;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemNagatoriumAmulet;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemOedldoedlRing;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemPantsu;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemPlumbob;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemPlunger;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemPylone;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemQuartariumAmulet;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemRedKyoryuuHorns;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemSakurajimariumAmulet;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemStrawHat;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemSunglasses;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemThreeDGlasses;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemThugLifeGlasses;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemToujouriumAmulet;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemTravellersWings;
import net.thep2wking.oedldoedlcuriosity.content.item.bauble.ItemWoodenBox;
import net.thep2wking.oedldoedlcuriosity.content.item.misc.ItemLoadingCase;
import net.thep2wking.oedldoedlcuriosity.content.item.misc.ItemProLoadingCase;

public class ModItems {
	public static final Item BAUBLE_PACKAGE = new ModItemBlockBase(ModBlocks.BAUBLE_PACKAGE, ModRarities.YELLOW, false, 2, 1);

	public static final Item BUNNY_EARS = new ItemBunnyEars(OedldoedlCuriosity.MODID, "bunny_ears", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.HEAD, false, MobEffects.JUMP_BOOST, 1, false, ModRarities.AQUA, false, 2, 0);
	public static final Item CAT_EARS = new ItemCatEars(OedldoedlCuriosity.MODID, "cat_ears", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.HEAD, false, ModRarities.AQUA, false, 1, 0);
	public static final Item RED_KYORYUU_HORNS = new ItemRedKyoryuuHorns(OedldoedlCuriosity.MODID, "red_kyoryuu_horns", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_GENERIC, BaubleType.HEAD, false, ModRarities.RED, false, 1, 0);
	public static final Item BLUE_KYORYUU_HORNS = new ItemBlueKyoryuuHorns(OedldoedlCuriosity.MODID, "blue_kyoryuu_horns", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_GENERIC, BaubleType.HEAD, false, ModRarities.BLUE, false, 1, 0);
	public static final Item DEVIL_HORNS = new ItemDevilHorns(OedldoedlCuriosity.MODID, "devil_horns", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_GENERIC, BaubleType.HEAD, false, ModRarities.RED, false, 1, 0);
	public static final Item PANTSU = new ItemPantsu(OedldoedlCuriosity.MODID, "pantsu", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.HEAD, false, ModRarities.AQUA, false, 1, 0);
	public static final Item MEGUMIN_PANTSU = new ItemMeguminPantsu(OedldoedlCuriosity.MODID, "megumin_pantsu", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.HEAD, false, ModRarities.YELLOW, false, 1, 0);
	public static final Item KITTY_HEADSET = new ItemKittyHeadset(OedldoedlCuriosity.MODID, "kitty_headset", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.HEAD, false, ModRarities.LIGHT_PURPLE, false, 2, 0);
	public static final Item MINEPODS_MAX = new ItemMinepodsMax(OedldoedlCuriosity.MODID, "minepods_max", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.HEAD, false, ModRarities.LIGHT_PURPLE, false, 2, 0);
	public static final Item PYLONE = new ItemPylone(OedldoedlCuriosity.MODID, "pylone", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_GENERIC, BaubleType.HEAD, false, ModRarities.AQUA, false, 1, 0);
	public static final Item PLUNGER = new ItemPlunger(OedldoedlCuriosity.MODID, "plunger", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_GENERIC, BaubleType.HEAD, false, ModRarities.AQUA, false, 1, 0);
	public static final Item TOP_HAT = new ItemTopHat(OedldoedlCuriosity.MODID, "top_hat", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.HEAD, false, ModRarities.AQUA, false, 1, 0);
	public static final Item MEGUMIN_HAT = new ItemMeguminHat(OedldoedlCuriosity.MODID, "megumin_hat", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.HEAD, false, MobEffects.FIRE_RESISTANCE, 0, false, ModRarities.RED, false, 1, 0);
	public static final Item CHAINSAW_HAT = new ItemChainsawHat(OedldoedlCuriosity.MODID, "chainsaw_hat", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.HEAD, false, MobEffects.STRENGTH, 1, false, ModRarities.RED, false, 1, 0);
	public static final Item CROWN = new ItemCrown(OedldoedlCuriosity.MODID, "crown", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, BaubleType.HEAD, false, MobEffects.LUCK, 4, false, ModRarities.GOLD, false, 1, 0);
	public static final Item FLYING_SHOOTING_BASECAP = new ItemFlyingShootingBasecap(OedldoedlCuriosity.MODID, "flying_shooting_basecap", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.HEAD, false, ModRarities.LIGHT_PURPLE, false, 2, 0);
	public static final Item BUNNY_CAP = new ItemBunnyCap(OedldoedlCuriosity.MODID, "bunny_cap", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.HEAD, false, ModRarities.AQUA, false, 1, 0);
	public static final Item STRAW_HAT = new ItemStrawHat(OedldoedlCuriosity.MODID, "straw_hat", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.HEAD, false, ModRarities.YELLOW, false, 1, 0);
	public static final Item BIRDS_NEST = new ItemBirdsNest(OedldoedlCuriosity.MODID, "birds_nest", OedldoedlCuriosity.TAB, SoundEvents.BLOCK_GRASS_PLACE, BaubleType.HEAD, false, ModRarities.YELLOW, false, 2, 0);
	public static final Item PLUMBOB = new ItemPlumbob(OedldoedlCuriosity.MODID, "plumbob", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, BaubleType.HEAD, false, ModRarities.GREEN, false, 1, 0);
	public static final Item GLASSES = new ItemGlasses(OedldoedlCuriosity.MODID, "glasses", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.HEAD, false, ModRarities.AQUA, false, 1, 0);
	public static final Item SUNGLASSES = new ItemSunglasses(OedldoedlCuriosity.MODID, "sunglasses", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.HEAD, false, ModRarities.AQUA, false, 1, 0);
	public static final Item FANCY_SUNGLASSES = new ItemFancySunglasses(OedldoedlCuriosity.MODID, "fancy_sunglasses", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.HEAD, false, ModRarities.AQUA, false, 2, 0);
	public static final Item AMAZING_TECHNICOLOR_GLASSES = new ItemAmazingTechnicolorGlasses(OedldoedlCuriosity.MODID, "amazing_technicolor_glasses", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.HEAD, false, MobEffects.NIGHT_VISION, 0, false, ModRarities.LIGHT_PURPLE, true, 1, 0);
	public static final Item THREE_D_GLASSES = new ItemThreeDGlasses(OedldoedlCuriosity.MODID, "3d_glasses", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.HEAD, false, ModRarities.BLUE, false, 1, 0);
	public static final Item THUG_LIFE_GLASSES = new ItemThugLifeGlasses(OedldoedlCuriosity.MODID, "thug_life_glasses", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.HEAD, false, ModRarities.LIGHT_PURPLE, false, 1, 0);
	public static final Item JOINT = new ItemJoint(OedldoedlCuriosity.MODID, "joint", OedldoedlCuriosity.TAB, SoundEvents.BLOCK_GRASS_PLACE, BaubleType.HEAD, false, ModRarities.GREEN, false, 1, 0);
	public static final Item LEAF_HEADBAND = new ItemLeafHeadband(OedldoedlCuriosity.MODID, "leaf_headband", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.HEAD, false, ModRarities.AQUA, false, 1, 0);
	public static final Item MONOCLE = new ItemMonocle(OedldoedlCuriosity.MODID, "monocle", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.HEAD, false, ModRarities.GOLD, false, 1, 0);
	public static final Item GOOGLY_EYES = new ItemGooglyEyes(OedldoedlCuriosity.MODID, "googly_eyes", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.HEAD, false, ModRarities.AQUA, false, 1, 0);
	public static final Item MOUSTAGE = new ItemMoustage(OedldoedlCuriosity.MODID, "moustage", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.HEAD, false, ModRarities.YELLOW, false, 1, 0);
	public static final Item FAKE_ARROW = new ItemFakeArrow(OedldoedlCuriosity.MODID, "fake_arrow", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_GENERIC, BaubleType.HEAD, false, ModRarities.AQUA, false, 1, 0);

	public static final Item WOODEN_BOX = new ItemWoodenBox(OedldoedlCuriosity.MODID, "wooden_box", OedldoedlCuriosity.TAB, SoundEvents.BLOCK_WOOD_PLACE, BaubleType.BODY, true, MobEffects.RESISTANCE, 1, false, ModRarities.LIGHT_PURPLE, false, 1, 0);
	public static final Item TRAVELLERS_WINGS = new ItemTravellersWings(OedldoedlCuriosity.MODID, "travellers_wings", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.BODY, true, MobEffects.JUMP_BOOST, 3, false, ModRarities.YELLOW, false, 1, 0);
	public static final Item DEMONIC_WINGS = new ItemDemonicWings(OedldoedlCuriosity.MODID, "demonic_wings", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.BODY, true, MobEffects.JUMP_BOOST, 4, false, ModRarities.LIGHT_PURPLE, false, 2, 0);
	public static final Item DEVIL_WINGS = new ItemDevilWings(OedldoedlCuriosity.MODID, "devil_wings", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.BODY, true, ModRarities.LIGHT_PURPLE, false, 1, 0);
	public static final Item DEVIL_TAIL = new ItemDevilTail(OedldoedlCuriosity.MODID, "devil_tail", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER, BaubleType.BODY, true, ModRarities.AQUA, false, 1, 0);
	
	public static final Item MINEPODS = new ItemMinepods(OedldoedlCuriosity.MODID, "minepods", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.CHARM, false, MobEffects.SPEED, 0, false, ModRarities.AQUA, false, 1, 0);
	public static final Item MINEPODS_PRO = new ItemMinepodsPro(OedldoedlCuriosity.MODID, "minepods_pro", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.CHARM, false, ModRarities.AQUA, false, 1, 0);

	public static final Item GREMORIUM_AMULET = new ItemGremoriumAmulet(OedldoedlCuriosity.MODID, "gremorium_amulet", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, BaubleType.AMULET, true, ModRarities.DARK_RED, true, 1, 0);
	public static final Item HIMEJIMARIUM_AMULET = new ItemHimejimariumAmulet(OedldoedlCuriosity.MODID, "himejimarium_amulet", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, BaubleType.AMULET, true, ModRarities.DARK_BLUE, true, 1, 0);
	public static final Item TOUJOURIUM_AMULET = new ItemToujouriumAmulet(OedldoedlCuriosity.MODID, "toujourium_amulet", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, BaubleType.AMULET, true, ModRarities.GRAY, true, 1, 0);
	public static final Item ARGENTORIUM_AMULET = new ItemArgentoriumAmulet(OedldoedlCuriosity.MODID, "argentorium_amulet", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, BaubleType.AMULET, true, ModRarities.YELLOW, true, 1, 0);
	public static final Item QUARTARIUM_AMULET = new ItemQuartariumAmulet(OedldoedlCuriosity.MODID, "quartarium_amulet", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, BaubleType.AMULET, true, ModRarities.BLUE, true, 1, 0);
	public static final Item NAGATORIUM_AMULET = new ItemNagatoriumAmulet(OedldoedlCuriosity.MODID, "nagatorium_amulet", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, BaubleType.AMULET, true, ModRarities.DARK_PURPLE, true, 1, 0);
	public static final Item SAKURAJIMARIUM_AMULET = new ItemSakurajimariumAmulet(OedldoedlCuriosity.MODID, "sakurajimarium_amulet", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, BaubleType.AMULET, true, ModRarities.DARK_GRAY, true, 1, 0);
	public static final Item KITAGAWARIUM_AMULET = new ItemKitagawariumAmulet(OedldoedlCuriosity.MODID, "kitagawarium_amulet", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, BaubleType.AMULET, true, ModRarities.LIGHT_PURPLE, true, 1, 0);

	public static final Item BALANCED_NECKLACE = new ItemBalancedNecklace(OedldoedlCuriosity.MODID, "balanced_necklace", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, BaubleType.AMULET, true, ModRarities.LIGHT_PURPLE, true, 1, 1);
		
	public static final Item BASE_RING = new ModItemBaubleBase(OedldoedlCuriosity.MODID, "base_ring", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.RING, false, ModRarities.WHITE, false, 1, 0).setNoRender();
	public static final Item BEDROCKIUM_RING = new ItemBedrockiumRing(OedldoedlCuriosity.MODID, "bedrockium_ring", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.RING, false, ModRarities.AQUA, false, 1, 0).setNoRender();
	public static final Item OEDLDOEDL_RING = new ItemOedldoedlRing(OedldoedlCuriosity.MODID, "oedldoedl_ring", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.RING, false, ModRarities.LIGHT_PURPLE, true, 1, 0).setNoRender();
	public static final Item ANGEL_RING = new ItemAngelRing(OedldoedlCuriosity.MODID, "angel_ring", OedldoedlCuriosity.TAB, SoundEvents.ITEM_ARMOR_EQUIP_IRON, BaubleType.RING, true, ModRarities.YELLOW, false, 1, 0);

	public static final Item LOADING_CASE = new ItemLoadingCase(OedldoedlCuriosity.MODID, "loading_case", OedldoedlCuriosity.TAB, ModRarities.YELLOW, false, 1, 0);
	public static final Item PRO_LOADING_CASE = new ItemProLoadingCase(OedldoedlCuriosity.MODID, "pro_loading_case", OedldoedlCuriosity.TAB, ModRarities.YELLOW, false, 1, 0);
	public static final Item MAGIC_FABRIC = new ModItemBase(OedldoedlCuriosity.MODID, "magic_fabric", OedldoedlCuriosity.TAB, ModRarities.RED, false, 1, 0);
	public static final Item SAFETY_PIN = new ModItemBase(OedldoedlCuriosity.MODID, "safety_pin", OedldoedlCuriosity.TAB, ModRarities.YELLOW, false, 1, 0);
	public static final Item ELECTRICAL_COMPONENT = new ModItemBase(OedldoedlCuriosity.MODID, "electrical_component", OedldoedlCuriosity.TAB, ModRarities.YELLOW, false, 1, 0);
	public static final Item SPEAKER = new ModItemBase(OedldoedlCuriosity.MODID, "speaker", OedldoedlCuriosity.TAB, ModRarities.YELLOW, false, 1, 0);
	public static final Item RUBBER_BAND = new ModItemBase(OedldoedlCuriosity.MODID, "rubber_band", OedldoedlCuriosity.TAB, ModRarities.YELLOW, false, 1, 0);
	public static final Item LENS = new ModItemBase(OedldoedlCuriosity.MODID, "lens", OedldoedlCuriosity.TAB, ModRarities.YELLOW, false, 1, 0);
}